TRUNCATE DATABASE wordbook;
CREATE DATABASE IF NOT EXISTS wordbook;
USE wordbook;

TRUNCATE TABLE books;
TRUNCATE TABLE contents;
TRUNCATE TABLE users;

-- ユーザテーブル
CREATE TABLE IF NOT EXISTS users (
    id UNSIGNED INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(10),
    email VARCHAR(20),
    password VARCHAR(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--  単語帳テーブル
CREATE TABLE IF NOT EXISTS books (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    user_id UNSIGNED INT NOT NULL,
    title VARCHAR(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id, user_id),
    FOREIGN KEY(user_id) REFERENCES users(id) on DELETE CASCADE
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- コンテンツテーブル
CREATE TABLE IF NOT EXISTS contents (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    book_id BIGINT(20) NOT NULL,
    user_id UNSIGNED INT NOT NULL,
    head TEXT,
    tail TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

